import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import { loadContext } from '../init/wizard';
import { MorphicContext } from '../init/defaults';

export async function generateGuidelines(opts: { output?: string }): Promise<void> {
  const context = loadContext();
  
  if (!context) {
    console.log(chalk.yellow('\n⚠️  No .morphic/context.json found. Run `morphic init` first.\n'));
    return;
  }

  const outputDir = path.resolve(opts.output || 'guidelines');
  
  console.log(chalk.bold('\n📚 Morphic — Generating Design System Guidelines\n'));

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Generate all guideline files
  writeFile(outputDir, 'README.md', generateReadme(context));
  writeFile(outputDir, 'tokens.md', generateTokensGuide(context));
  writeFile(outputDir, 'components.md', generateComponentsGuide(context));
  writeFile(outputDir, 'patterns.md', generatePatternsGuide(context));
  writeFile(outputDir, 'accessibility.md', generateAccessibilityGuide(context));
  writeFile(outputDir, 'rules.md', generateRulesGuide(context));

  // Generate CLAUDE.md at project root
  const claudeMd = generateClaudeMd(context, outputDir);
  const claudePath = path.resolve(process.cwd(), 'CLAUDE.md');
  fs.writeFileSync(claudePath, claudeMd);

  console.log(chalk.green('✅ Generated guidelines:\n'));
  console.log(chalk.gray(`  ${path.relative(process.cwd(), outputDir)}/`));
  console.log(chalk.gray('  ├── README.md         — Overview & quick reference'));
  console.log(chalk.gray('  ├── tokens.md         — Colors, spacing, typography, shadows'));
  console.log(chalk.gray('  ├── components.md     — Component patterns & usage'));
  console.log(chalk.gray('  ├── patterns.md       — Layout & page patterns'));
  console.log(chalk.gray('  ├── accessibility.md  — WCAG rules & checklist'));
  console.log(chalk.gray('  └── rules.md          — All design system rules'));
  console.log(chalk.gray(`\n  CLAUDE.md             — LLM entry point (references guidelines/)`));
  console.log(chalk.cyan(`\nLLMs will automatically read CLAUDE.md → guidelines/ when generating code.\n`));
}

function generateClaudeMd(ctx: MorphicContext, guidelinesDir: string): string {
  const relDir = path.relative(process.cwd(), guidelinesDir);
  return `# CLAUDE.md — Design System Context

This project uses a custom design system. Follow these guidelines when generating UI code.

## Stack
- **Framework:** ${ctx.stack.framework}
- **UI/CSS:** ${ctx.stack.ui} (${ctx.stack.cssApproach})
- **Language:** ${ctx.stack.language}

## Quick Rules
${ctx.rules.map((r, i) => `${i + 1}. ${r}`).join('\n')}

## Accessibility
- Target: **WCAG ${ctx.accessibility.level}**
- Min contrast: **${ctx.accessibility.minContrast}:1**
- Min touch target: **${ctx.accessibility.minTouchTarget}**

## Key Tokens
- Primary: \`${ctx.tokens.colors.primary}\`
- Spacing scale: \`${ctx.tokens.spacing.join(', ')}\`
- Font: \`${ctx.tokens.typography.fontFamily}\`
- Border radius: ${Object.entries(ctx.tokens.radii).map(([k, v]) => `${k}=${v}`).join(', ')}

## Detailed Guidelines
Read these files before generating UI code:
- [\`${relDir}/tokens.md\`](./${relDir}/tokens.md) — All design tokens (colors, spacing, typography, shadows, radii)
- [\`${relDir}/components.md\`](./${relDir}/components.md) — Component patterns, do/don't examples
- [\`${relDir}/patterns.md\`](./${relDir}/patterns.md) — Layout patterns, page structures, grid systems
- [\`${relDir}/accessibility.md\`](./${relDir}/accessibility.md) — WCAG compliance, ARIA, keyboard nav
- [\`${relDir}/rules.md\`](./${relDir}/rules.md) — Complete rule reference

## When Generating Code
1. Use design tokens — never hardcode colors, spacing, or typography
2. Follow component patterns in \`${relDir}/components.md\`
3. Check accessibility requirements in \`${relDir}/accessibility.md\`
4. Use layout patterns from \`${relDir}/patterns.md\`
5. Run \`morphic lint ./src\` after generating to verify compliance
`;
}

function generateReadme(ctx: MorphicContext): string {
  return `# Design System Guidelines

> Auto-generated by Morphic. Edit \`.morphic/context.json\` and run \`morphic guidelines\` to regenerate.

## Stack
| | |
|---|---|
| Framework | ${ctx.stack.framework} |
| UI Library | ${ctx.stack.ui} |
| Language | ${ctx.stack.language} |
| CSS Approach | ${ctx.stack.cssApproach} |

## Quick Reference

### Colors
${Object.entries(ctx.tokens.colors).map(([name, value]) => `- \`${name}\`: \`${value}\``).join('\n')}

### Spacing Scale
\`${ctx.tokens.spacing.join(' | ')}\` (px)

### Typography
- Font: \`${ctx.tokens.typography.fontFamily}\`
- Sizes: ${Object.entries(ctx.tokens.typography.sizes).map(([k, v]) => `${k}=${v}`).join(', ')}

### Accessibility Target
WCAG **${ctx.accessibility.level}** — min contrast ${ctx.accessibility.minContrast}:1

## Files
- [tokens.md](./tokens.md) — Complete token reference
- [components.md](./components.md) — Component guidelines
- [patterns.md](./patterns.md) — Layout patterns
- [accessibility.md](./accessibility.md) — A11y standards
- [rules.md](./rules.md) — Development rules
`;
}

function generateTokensGuide(ctx: MorphicContext): string {
  return `# Design Tokens

> Use these tokens everywhere. Never hardcode values.

## Colors

| Token | Value | Usage |
|-------|-------|-------|
${Object.entries(ctx.tokens.colors).map(([name, value]) => 
  `| \`${name}\` | \`${value}\` | ${getColorUsage(name)} |`
).join('\n')}

### Usage
\`\`\`tsx
// ✅ Do
<button className="bg-primary text-white hover:bg-primary-hover">
<p className="text-foreground-muted">

// ❌ Don't
<button style={{ backgroundColor: '${ctx.tokens.colors.primary}' }}>
<p style={{ color: '#64748B' }}>
\`\`\`

## Spacing

Allowed values: \`${ctx.tokens.spacing.join(', ')}\` (px)

| Value | Tailwind | Use For |
|-------|----------|---------|
${ctx.tokens.spacing.filter(s => s > 0).map(s => 
  `| ${s}px | \`p-${s/4}\` / \`gap-${s/4}\` | ${getSpacingUsage(s)} |`
).join('\n')}

### Usage
\`\`\`tsx
// ✅ Do — values from the scale
<div className="p-4 gap-6">     // 16px, 24px
<div className="mt-8 mb-16">    // 32px, 64px

// ❌ Don't — arbitrary values
<div className="p-[13px] gap-[22px]">
<div style={{ margin: '15px' }}>
\`\`\`

## Typography

**Font Family:** \`${ctx.tokens.typography.fontFamily}\`

### Sizes
| Token | Value | Use For |
|-------|-------|---------|
${Object.entries(ctx.tokens.typography.sizes).map(([name, size]) => 
  `| \`${name}\` | \`${size}\` | ${getTypoUsage(name)} |`
).join('\n')}

### Weights
| Token | Value |
|-------|-------|
${Object.entries(ctx.tokens.typography.weights).map(([name, weight]) => 
  `| \`${name}\` | \`${weight}\` |`
).join('\n')}

### Line Heights
| Token | Value |
|-------|-------|
${Object.entries(ctx.tokens.typography.lineHeights).map(([name, lh]) => 
  `| \`${name}\` | \`${lh}\` |`
).join('\n')}

### Usage
\`\`\`tsx
<h1 className="text-4xl font-bold">        // Page title
<h2 className="text-2xl font-bold">        // Section heading
<h3 className="text-xl font-semibold">     // Card title
<p className="text-base">                   // Body text
<span className="text-sm text-gray-600">   // Supporting text
<small className="text-xs text-gray-500">  // Caption
\`\`\`

## Border Radius

| Token | Value |
|-------|-------|
${Object.entries(ctx.tokens.radii).map(([name, value]) => 
  `| \`${name}\` | \`${value}\` |`
).join('\n')}

### Usage
\`\`\`tsx
<button className="rounded-lg">     // Buttons: lg (12px)
<div className="rounded-xl">        // Cards: xl (16px)
<span className="rounded-full">     // Badges/avatars: full
<input className="rounded-lg">      // Inputs: lg (12px)
\`\`\`

## Shadows

| Token | Value |
|-------|-------|
${Object.entries(ctx.tokens.shadows).map(([name, value]) => 
  `| \`${name}\` | \`${value}\` |`
).join('\n')}

## Breakpoints

| Token | Value | Description |
|-------|-------|-------------|
${Object.entries(ctx.tokens.breakpoints).map(([name, value]) => 
  `| \`${name}\` | \`${value}\` | ${getBreakpointDesc(name)} |`
).join('\n')}
`;
}

function generateComponentsGuide(ctx: MorphicContext): string {
  return `# Component Guidelines

## Button

### Variants
\`\`\`tsx
// Primary — main actions (1 per visible area)
<button className="bg-primary text-white px-6 py-3 rounded-lg font-semibold 
  hover:bg-primary-hover focus-visible:outline focus-visible:outline-2 
  focus-visible:outline-offset-2 focus-visible:outline-primary transition-colors">
  Get Started
</button>

// Secondary — alternative actions
<button className="border border-gray-300 px-6 py-3 rounded-lg font-semibold 
  text-gray-900 hover:bg-gray-50 transition-colors">
  Learn More
</button>

// Destructive — dangerous actions
<button className="bg-error text-white px-6 py-3 rounded-lg font-semibold 
  hover:bg-red-600 transition-colors">
  Delete
</button>
\`\`\`

### Rules
- ✅ One primary button per visible area
- ✅ Always include \`aria-label\` on icon-only buttons
- ✅ Min touch target: ${ctx.accessibility.minTouchTarget}
- ✅ Always show focus styles (\`focus-visible:outline\`)
- ❌ Don't use \`<div onClick>\` — use \`<button>\`
- ❌ Don't disable without explanation

## Card

\`\`\`tsx
<div className="rounded-xl border border-gray-200 p-6 hover:shadow-md transition-shadow">
  <h3 className="text-xl font-semibold">{title}</h3>
  <p className="mt-2 text-sm text-gray-600">{description}</p>
</div>
\`\`\`

### Rules
- ✅ Use \`rounded-xl\` and \`border border-gray-200\`
- ✅ Padding: \`p-6\` or \`p-8\`
- ✅ Add \`hover:shadow-md transition-shadow\` for interactive cards

## Form Input

\`\`\`tsx
<div>
  <label htmlFor="email" className="block text-sm font-medium text-gray-700">
    Email <span className="text-error" aria-hidden="true">*</span>
  </label>
  <input
    id="email"
    type="email"
    required
    aria-required="true"
    aria-describedby="email-error"
    className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-2
      focus:border-primary focus:ring-primary"
  />
  <p id="email-error" role="alert" className="mt-1 text-sm text-error">
    Please enter a valid email
  </p>
</div>
\`\`\`

### Rules
- ✅ Always associate \`<label>\` with \`htmlFor\`
- ✅ Use \`aria-required\` and \`aria-describedby\` for validation
- ✅ Error messages with \`role="alert"\`
- ❌ Don't use placeholder as the only label
- ❌ Don't rely on color alone for error state

## Navigation

\`\`\`tsx
<nav className="border-b border-gray-200 bg-white" aria-label="Main navigation">
  <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4">
    <a href="/" className="text-xl font-bold">{brand}</a>
    <ul className="flex gap-8">
      <li><a href="/features" className="text-sm font-medium text-gray-600 hover:text-gray-900">Features</a></li>
      <li><a href="/pricing" className="text-sm font-medium text-primary" aria-current="page">Pricing</a></li>
    </ul>
  </div>
</nav>
\`\`\`

### Rules
- ✅ Use \`<nav>\` with \`aria-label\`
- ✅ Mark current page with \`aria-current="page"\`
- ✅ Include mobile hamburger menu for responsive

## File Structure

\`\`\`
${ctx.patterns.componentDir}/
├── Button${ctx.patterns.fileExtension}
├── Card${ctx.patterns.fileExtension}
├── DataTable${ctx.patterns.fileExtension}
├── Form${ctx.patterns.fileExtension}
└── Navigation${ctx.patterns.fileExtension}
\`\`\`

- Naming: **${ctx.patterns.namingConvention}**
- Extension: **${ctx.patterns.fileExtension}**
- One component per file
- Export as default
`;
}

function generatePatternsGuide(ctx: MorphicContext): string {
  return `# Layout Patterns

## Page Structure

\`\`\`tsx
<main className="min-h-screen">
  <section className="mx-auto max-w-7xl px-4 py-24">
    {/* Page content */}
  </section>
</main>
\`\`\`

## Content Width

| Type | Class | Width | Use For |
|------|-------|-------|---------|
| Narrow | \`max-w-2xl\` | 672px | Forms, auth, articles |
| Medium | \`max-w-4xl\` | 896px | Settings, detail pages |
| Wide | \`max-w-7xl\` | 1280px | Dashboards, landing pages |
| Full | (none) | 100% | Backgrounds, hero sections |

## Grid Systems

\`\`\`tsx
// Feature grid (3 cols)
<div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">

// Stats row (4 cols)
<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">

// Dashboard (main + sidebar)
<div className="grid gap-8 lg:grid-cols-3">
  <section className="lg:col-span-2">{/* Main */}</section>
  <aside>{/* Sidebar */}</aside>
</div>

// Two column
<div className="grid gap-16 lg:grid-cols-2 items-center">
\`\`\`

## Spacing Between Sections

| Context | Class | Value |
|---------|-------|-------|
| Between page sections | \`py-24\` | 96px |
| Section to heading | \`mb-16\` | 64px |
| Between cards/items | \`gap-8\` | 32px |
| Inside cards | \`p-6\` or \`p-8\` | 24-32px |
| Between form fields | \`space-y-6\` | 24px |
| Text to text | \`mt-2\` to \`mt-4\` | 8-16px |

## Hero Pattern

\`\`\`tsx
<section className="flex flex-col items-center px-4 py-24 text-center">
  <span className="mb-4 rounded-full bg-blue-100 px-4 py-1.5 text-sm font-semibold text-primary">
    Badge
  </span>
  <h1 className="max-w-3xl text-5xl font-bold tracking-tight sm:text-6xl">
    Headline Here
  </h1>
  <p className="mt-6 max-w-2xl text-lg text-gray-600">
    Supporting text that explains the value proposition.
  </p>
  <div className="mt-10 flex gap-4">
    <a href="#" className="rounded-lg bg-primary px-6 py-3 font-semibold text-white">Primary CTA</a>
    <a href="#" className="rounded-lg border border-gray-300 px-6 py-3 font-semibold">Secondary CTA</a>
  </div>
</section>
\`\`\`

## Pricing Pattern

\`\`\`tsx
<div className="grid gap-8 lg:grid-cols-3">
  {plans.map((plan) => (
    <div className={\`flex flex-col rounded-2xl border p-8 \${
      plan.highlighted ? 'border-primary ring-2 ring-primary shadow-lg' : 'border-gray-200'
    }\`}>
      <h2 className="text-2xl font-bold">{plan.name}</h2>
      <p className="mt-2 text-gray-600">{plan.description}</p>
      <p className="mt-6"><span className="text-4xl font-bold">{plan.price}</span>/mo</p>
      <ul className="mt-8 flex-1 space-y-3">{/* features */}</ul>
      <button className="mt-8 w-full rounded-lg px-4 py-3 font-semibold">{plan.cta}</button>
    </div>
  ))}
</div>
\`\`\`

## Available Templates

Generate these with \`morphic generate\`:

**Pages:** landing, pricing, dashboard, settings, auth, 404
**Components:** form, data-table, card-grid, navigation, hero
`;
}

function generateAccessibilityGuide(ctx: MorphicContext): string {
  return `# Accessibility Standards

**Target: WCAG ${ctx.accessibility.level}**

## Requirements

| Requirement | Value |
|-------------|-------|
| WCAG Level | ${ctx.accessibility.level} |
| Min contrast (normal text) | ${ctx.accessibility.minContrast}:1 |
| Min contrast (large text) | 3:1 |
| Min touch target | ${ctx.accessibility.minTouchTarget} |
| Alt text required | ${ctx.accessibility.requireAltText ? 'Yes' : 'No'} |
| ARIA labels required | ${ctx.accessibility.requireAriaLabels ? 'Yes' : 'No'} |

## Semantic HTML

Always use semantic elements:

\`\`\`tsx
// ✅ Do
<nav aria-label="Main navigation">
<main>
<section aria-labelledby="features-heading">
<article>
<aside aria-labelledby="sidebar-heading">
<footer>
<button onClick={handle}>
<a href="/page">

// ❌ Don't
<div className="nav">
<div className="main">
<div onClick={handle}>   // Use <button>
<span onClick={handle}>  // Use <button> or <a>
\`\`\`

## Images

\`\`\`tsx
// Informative — descriptive alt
<img src="chart.png" alt="Revenue grew 45% in Q3" />

// Decorative — empty alt
<img src="decoration.svg" alt="" aria-hidden="true" />

// ❌ Never
<img src="photo.jpg" />  // Missing alt
\`\`\`

## Interactive Elements

\`\`\`tsx
// Icon-only button — needs aria-label
<button aria-label="Close dialog">
  <XIcon aria-hidden="true" />
</button>

// Focus styles — always visible
<button className="focus-visible:outline focus-visible:outline-2 
  focus-visible:outline-offset-2 focus-visible:outline-primary">

// onClick on div — add role and keyboard handler
<div role="button" tabIndex={0} onClick={handle} onKeyDown={handleKey}>
\`\`\`

## Forms

\`\`\`tsx
// ✅ Complete accessible form
<form aria-label="Sign up form">
  <div>
    <label htmlFor="name">Name <span aria-hidden="true">*</span></label>
    <input id="name" required aria-required="true" />
  </div>
  <div>
    <label htmlFor="email">Email</label>
    <input id="email" type="email" aria-describedby="email-hint" />
    <p id="email-hint" className="text-sm text-gray-500">We'll never share your email</p>
  </div>
</form>

// ❌ Inaccessible form
<input placeholder="Name" />           // No label
<input type="email" />                  // No label, no association
<div className="error">Invalid</div>   // Not linked to input
\`\`\`

## Keyboard Navigation

- All interactive elements reachable via Tab
- Focus order follows visual layout
- Escape closes modals/dropdowns/popovers
- Modals trap focus
- Return focus to trigger on modal close
- Arrow keys for menus/tabs/radio groups

## Color

- Never use color as the only indicator
- Error: use icon + text + color
- Status: use icon + label, not just color

## Checklist

Before shipping, verify:
- [ ] Tab through entire page — all interactive elements reachable?
- [ ] Screen reader makes sense? (VoiceOver: Cmd+F5 on Mac)
- [ ] Zoom to 200% — everything usable?
- [ ] All images have alt text?
- [ ] All forms have labels?
- [ ] Focus styles visible on all interactive elements?
- [ ] Sufficient color contrast?
- [ ] \`morphic lint ./src\` passes?
`;
}

function generateRulesGuide(ctx: MorphicContext): string {
  return `# Design System Rules

${ctx.rules.map((rule, i) => `## Rule ${i + 1}

**${rule}**

`).join('\n')}

## Enforcement

Run \`morphic lint ./src\` to check compliance:

\`\`\`bash
# Check all files
morphic lint ./src

# Auto-fix where possible
morphic lint --fix ./src

# JSON output for CI
morphic lint ./src --format json

# Exit code 1 on errors (CI mode)
morphic lint ./src --format json && echo "PASS" || echo "FAIL"
\`\`\`
`;
}

// Helpers
function getColorUsage(name: string): string {
  const map: Record<string, string> = {
    primary: 'Buttons, links, active states',
    'primary-hover': 'Hover state for primary',
    secondary: 'Secondary text, icons',
    'secondary-hover': 'Hover state for secondary',
    success: 'Success messages, positive states',
    warning: 'Warnings, caution states',
    error: 'Errors, destructive actions',
    background: 'Page background',
    'background-secondary': 'Card backgrounds, sections',
    foreground: 'Primary text',
    'foreground-muted': 'Secondary text, descriptions',
    border: 'Borders, dividers',
  };
  return map[name] || '';
}

function getSpacingUsage(s: number): string {
  if (s <= 4) return 'Tight spacing, icon gaps';
  if (s <= 8) return 'Inline padding, small gaps';
  if (s <= 12) return 'Input padding, compact spacing';
  if (s <= 16) return 'Default padding, form gaps';
  if (s <= 24) return 'Card padding, section gaps';
  if (s <= 32) return 'Between components';
  if (s <= 48) return 'Section spacing';
  return 'Page-level spacing';
}

function getTypoUsage(name: string): string {
  const map: Record<string, string> = {
    xs: 'Captions, badges',
    sm: 'Supporting text, labels',
    base: 'Body text',
    lg: 'Large body, intro text',
    xl: 'Card titles, H3',
    '2xl': 'Section headings, H2',
    '3xl': 'Page titles',
    '4xl': 'Hero headings, H1',
  };
  return map[name] || '';
}

function getBreakpointDesc(name: string): string {
  const map: Record<string, string> = {
    sm: 'Large phones',
    md: 'Tablets',
    lg: 'Small laptops',
    xl: 'Desktops',
    '2xl': 'Large screens',
  };
  return map[name] || '';
}

function writeFile(dir: string, filePath: string, content: string): void {
  const fullPath = path.join(dir, filePath);
  fs.writeFileSync(fullPath, content);
}
